services:
  mongo:
    image: mongo:7
    container_name: smitfinal_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: umer
      MONGO_INITDB_ROOT_PASSWORD: umer1234

  mongo-express:
      image: mongo-express:1.0
      container_name: smitfinal_mongo_express
      restart: unless-stopped
      ports:
        - "8082:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: umer
        ME_CONFIG_MONGODB_ADMINPASSWORD: umer1234
        ME_CONFIG_MONGODB_SERVER: mongo
      depends_on:
        - mongo

volumes:
  mongo-data:
    
